config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"

  root 'categories#index'
  
  resources :articles do
    resources :comments, only: [:create]
  end
  resources :categories
  resources :votes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100,
                                              too_long: '100 characters in article\'s title is the maximum allowed.' }

  validates :text, presence: true
  validates :author_id, presence: true

  belongs_to :author, class_name: 'User'

  has_one_attached :photo, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :comments, dependent: :destroy

  has_and_belongs_to_many :categories

  validates :photo, presence: true
  validates :categories, presence: true

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :priority, presence: true, uniqueness: true

  scope :ordered_by_priority, -> { order(:priority) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200,
                                                too_long: '200 characters in comment is the maximum allowed.' }

  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true

  has_many :articles, class_name: :Article, foreign_key: 'author_id'

  has_many :votes, dependent: :destroy
  has_many :voted_article, through: :votes, source: :article

  has_many :comments, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :user_id, uniqueness: { scope: :article_id }

  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      @article.category_ids = article_params[:category_ids]
      redirect_to root_path, notice: 'Article was successfully created.'
    else
      redirect_to root_path, alert: 'Something went wrong, and Article was not created.'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:author_id, :title, :text, :photo, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    categories
    @featued_article = Article.all.joins(:votes).group('articles.id').order('count(articles.id) DESC').first
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.ordered_by_most_recent
  end

  private

  def categories
    @categories = Category.all.order(:priority).includes(:articles)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.user = current_user

    if @comment.save
      redirect_to article_path(params[:article_id]), notice: 'Comment was successfully created.'
    else
      redirect_to article_path(params[:article_id]), alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
  end

  def create
    @vote = current_user.votes.new(article_id: params[:article_id])

    if @vote.save
      redirect_to article_path(params[:article_id]), notice: 'You gave a vote to this article'
    else
      redirect_to article_path(params[:article_id]), alert: 'You cannot give a vote to this article'
    end
  end

  def destroy
    vote = Vote.find_by(id: params[:id], user_id: current_user.id, article_id: params[:article_id])

    if vote
      vote.destroy
      redirect_to article_path(params[:article_id]), notice: 'You unvote this article'
    else
      redirect_to article_path(params[:article_id]), notice: 'You cannot unvote this article'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'nav-link active' : 'nav-link'
    link_to link_text, link_path, class: class_name
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def display_errors(article)
    return unless article.errors.full_messages.any?

    content_tag :p, "Article could not be saved. #{article.errors.full_messages.join('. ')}", class: 'errors'
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def featued_image(featued_article)
    image_tag featued_article.photo, class: 'img-fluid p-0 w-100' if featued_article.photo.attached?
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_unvote_option(article)
    vote = Vote.find_by(user_id: current_user[:id], article_id: article[:id])

    if vote
      button_to('', vote_path(id: vote.id, article_id: article.id), method: :delete, class: 'border-0 bg-transparent vote voted')
    else
      button_to('', votes_path(article_id: article.id), method: :post, class: 'border-0 bg-transparent vote unvoted')
    end
  end
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>

  <div class="my-3">
    <h4 class='text-center life-style-brown-color fw-bold'>New Article Form</h4>
    <div class="form_field my-4">
      <%= form.label :title, class: 'form-label life-style-brown-color' %>
      <%= form.text_field :title, id: :article_title, class: 'form-control', placeholder: 'Article Title' %>
      <div id="emailHelp" class="form-text">The maximum characters allowed in article's title is 100.</div>
    </div>
      
    <div class="form_field my-4">
      <%= form.label :text, 'Content', class: 'form-label life-style-brown-color fw-bold' %>
      <%= form.text_area :text, id: :article_text, class: 'form-control', placeholder: 'Article Content', rows: '12' %>
    </div>

    <div class="form_field my-4">
      <%= form.label :category, class: 'form-label life-style-brown-color fw-bold' %>
      <div class="categories-check-boxes">
        <%= form.collection_check_boxes :category_ids, Category.order(:priority), :id, :name %>
      </div>
    </div>

    <div class="form_field my-4">
      <%= form.label :photo,  class: 'form-label life-style-brown-color fw-bold' %>
      <%= form.file_field :photo, class: 'form-control'%>
    </div>

    <div class="form_field my-4 text-center">
      <%= form.submit 'Save', class: 'btn life-style-btn-primary shadow-sm px-5 mx-auto mt-3 w-50 life-style-orange-bg-color' %>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>YOU ARE HERE MY FRIEND</h1>

app/views/articles/new.html.erb
<div class='w-50 mx-auto bg-white shadow px-5 py-3 my-5'>
    <%= render partial: "form", locals: {article: @article} %>
</div>

app/views/articles/show.html.erb
<div class="container py-5">
  	<div class="row mb-4">
      <% if @article.photo.attached? %>
		<%= image_tag @article.photo, class:"img-fluid" %>
	  <% end %>
	</div>

	<div class="row mb-4">
		<h3 class="fw-bold life-style-orange-color text-center m-0"><%= @article.title %></h3>
	</div>

	<div class="row w-75 text-center mx-auto mb-4">
		<p class="lh-lg"><%= @article.text %></p>
	</div>

	<div class="row w-75 mx-auto">
		<div class="d-flex justify-content-between px-0 mb-3">
			<h5 class="life-style-brown-color fw-bold">comments</h5>
			<%= vote_unvote_option(@article) %>
		</div>

		<div class="px-0">
		    <div class='article-comments-section'>
    			<%= render partial: 'comments/comment', collection: @article.comments %>

				<%= form_for(@article.comments.new, url: article_comments_path(@article)) do |form| %>
					<%= form.text_area :content, class: 'w-75 form-control', rows: '2', cols:'50', placeholder: 'write a comment' %>
					<%= form.submit 'Add a comment', class: 'btn life-style-btn-primary shadow-sm px-5 mt-3 w-25' %>
				<% end %>
  			</div>
		</div>
	</div>
</div>

app/views/categories/_category.html.erb
<% if category.articles.ordered_by_most_recent.first %>
    <%= image_tag category.articles.ordered_by_most_recent.first.photo if category.articles.ordered_by_most_recent.first.photo.attached? %>
    <div class="overlay"> </div>
    <a href="<%= category_path(category.id) %>" class="d-block">
        <h5 class="text-white ms-4 fw-bold"> <%= category.name %> </h5>
    </a>
    <h5 class="text-white ms-4 truncate w-75"> <%= category.articles.ordered_by_most_recent.first.title %> </h5>
<% else %>
    <%= link_to category.name, category_path(category), class: 'life-style-grey-color text-center py-3 d-block' %>
<% end %>

app/views/categories/index.html.erb
<div class="container-fluid px-0">
  <div class="row position-relative featued_article w-100 m-0">
    <% if @featued_article %>
    <a href="<%= article_path(@featued_article.id) %>" class="px-0">
        <%= featued_image(@featued_article) %>

        <div class="overlay w-100"> </div>

        <div class="article-description d-flex justify-content-between px-0 w-100">
          <div class="headline w-75">

            <h4 class="life-style-orange-color fw-bold px-4">
              <%=  @featued_article.title %>
            </h4>

            <p class="text-white w-100 px-4 truncate"> <%= @featued_article.text %> </p>

          </div>

          <div class="votes px-4 d-flex">
            <span class="vote voted mx-1"></span>
            <span class="text-white mx-1"><%= @featued_article.votes.size %></span>
          </div>
      </div>
     </a>
    <% end %>
  </div>
  
  <div class="row mx-0 w-100">
    <% @categories.each do |category| %>
      <div class="col-md-6 col-lg-3 position-relative category-card px-0">
        <%= render partial: "category", locals: {category: category} %>    
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
  <div class="row general-article-container">
    <% @articles.each do |article| %>
      <div class="col-md-6 article-container p-0">
        <div class="d-flex h-100">
          <div class="w-50 image-container">
            <% if article.photo.attached? %>
              <%= image_tag article.photo, class:"" %>
            <% end %>
          </div>
          <div class="w-50 p-3">
            <h4 class="fw-bold life-style-orange-color border-bottom-orange d-inline-block mb-3"><%= @category.name %></h4>
            <h6 class="fw-bold mb-3"><%= article.title %></h6>
            <p class="h-truncate"><%=  article.text %></p>
            <%= link_to 'Read More', article_path(article), class:'life-style-orange-color text-decoration-none'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="d-flex justify-content-between">
  <b><%= comment.user.name %></b> 
  <span> <%= comment.created_at.strftime("%d/%m/%y") %> </span>
</div>
<p>
  <%= comment.content %>
</p>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeStyle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar sticky-top navbar-light bg-white shadow-sm">
      <div class="container-fluid">
        <div>
          <%= link_to 'LiFEsTYLe', root_path, class: 'navbar-brand mb-0 me-5 h1' %>

          <% if current_user %>
            <div class="d-inline-block">
              <ul class="navbar-nav d-flex flex-row mx-5">
                <li class="nav-item me-3 text-uppercase">
                  <%= menu_link_to 'Home', root_path%>
                </li>
                <li class="nav-item text-uppercase me-3">
                  <%= menu_link_to 'Write an article', new_article_path%>
                </li>
                <% Category.all.ordered_by_priority.each do |category| %>
                  <li class="nav-item text-uppercase me-3">
                     <%= menu_link_to category.name, category_path(category)%>
                  </li>
                <% end %>
              </ul>
          </div>
         <% end %>
        </div>

        <% if current_user %>
          <div>
            <%= link_to 'LOG OUT', users_sign_out_path, class: 'nav-link' %>
          </div>
        <% end %>
        <% if !current_user %>
          <div>
            <%= link_to 'LOG IN', new_user_session_path, class: 'nav-link' %>
          </div>
        <% end %>

      </div>
    </nav>

    <div class="life-style-flashes-container">
      <% if notice.present? %>
        <div class="life-style-notice-flash shadow" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="life-style-notice-bg-color py-2 px-3">
            <%= content_tag(:span, notice, class:"text-white") %>
          </div>
        </div>
      <% end %>
      
      <% if alert.present? %>
        <div class="life-style-alert-flash shadow" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="life-style-alert-bg-color py-2 px-3">
            <%= content_tag(:span, alert, class:"text-white") %>
          </div>
        </div>
      <% end %>
    </div>
    
    <div class="general-min-height">
      <%= yield %>
    </div>

    <% if current_user %>
      <footer class="footer mt-auto py-3 life-style-brown-bg-color text-white">
        <div class="container-fluid d-flex justify-content-between align-items-center">
          <div>
            <%= link_to 'LiFEsTYLe', root_path, class: 'navbar-brand mb-0 me-5 h1 text-white link-none-hover' %>

            <div class="d-inline-block">
              <ul class="navbar-nav d-flex flex-row align-items-center mx-5">
                <li class="nav-item me-3">
                  <%= link_to  'Privacy Policy', root_path, class:'life-style-orange-color link-hover-orange-color' %>
                </li>
                <li class="nav-item me-3">
                  <%= link_to 'Terms & Conditions', root_path, class:'life-style-orange-color link-hover-orange-color' %>
                </li>
                  <li class="nav-item me-3">
                     <span>Copyright 2021. All rights reserved</span>
                  </li>
              </ul>
            </div>
          </div>

          <div class="px-3 d-flex align-items-center">
            <span>Connect with us: </span>
            <ul class="nav justify-content-end">
              <li class="nav-item social-media twitter px-1 pt-1"><a href="#"></a></li>
              <li class="nav-item social-media instgram px-1 pt-1"><a href="#"></a></li>
              <li class="nav-item social-media facebook px-1 pt-1"><a href="#"></a></li>
            </ul>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>